plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-archives
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "neon"
locale: "en-US"
title: "NetworkChunks"
title_separator: "-"
subtitle: "by Pavan Vemuri"
name: "Pavan Vemuri"
description: "An amazing website."
url: "https://networkchunks.com"
#baseurl: "/networkchunks"
repository: "PAVAN-VEMURI/networkchunks"
breadcrumbs: true
head_scripts:
  - https://code.jquery.com/jquery-3.2.1.min.js

atom_feed:
  hide: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

logo: "/assets/images/nchunkslogo.png"
masthead_title: "Network Chunks"

comments:
  provider: "giscus"
  giscus:
    repo_id              : "R_kgDOGgqc3g"
    category_name        : "General"
    category_id          : "DIC_kwDOGgqc3s4CAO0z" # Shown during giscus setup at https://giscus.app
    discussion_term      : "pathname" # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : '1' # '1' for enabled (default), '0' for disabled
    theme: "dark"
