plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-archives
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"
locale: "en-US"
title: "NetworkChunks"
title_separator: "-"
subtitle: "by Pavan Vemuri"
name: "Pavan Vemuri"
description: "An amazing website."
url: "https://networkchunks.com"
#baseurl: "/networkchunks"
repository: "PAVAN-VEMURI/networkchunks"
breadcrumbs: true
search: true
head_scripts:
  - https://code.jquery.com/jquery-3.2.1.min.js
teaser: "/assets/images/nchunkslogo.png"
atom_feed:
  hide: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

logo: "/assets/images/nchunkslogo.png"
masthead_title: "Network Chunks"

comments:
  provider: "giscus"
  giscus:
    repo_id              : "R_kgDOGgqc3g"
    category_name        : "General"
    category_id          : "DIC_kwDOGgqc3s4CAO0z" # Shown during giscus setup at https://giscus.app
    discussion_term      : "pathname" # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : '1' # '1' for enabled (default), '0' for disabled
    theme: "dark"

author:
  name     : "Pavan Vemuri"
  avatar   : "/assets/images/nchunkslogo.png"
  bio      : "A computer science graduate, tech enthusiast, nature and animal lover. I like to solve problems, learn new
  things and most importantly I love riding around the world."
  location : "Somewhere, India"
  links:
    - label: "NetworkChunks"
      icon: "fas fa-fw fa-link"
      url: "https://networkchunks.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/vpavan318"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/PAVAN-VEMURI"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/edo_tensei_2.0/"
